version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: 'gossip-air'
    ports:
      - 8910:8910
    volumes:
      - ./server/:/app/

  db:
    image: postgres
    container_name: 'gossip-pg'
    ports:
      - 6543:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: gossip
      POSTGRES_DB: gossip
volumes:
  postgres-data:
