version: '3.9'

services:
  db:
    image: postgres
    container_name: 'pg-gossip'
    ports:
      - 6543:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: gossip
      POSTGRES_DB: gossip
volumes:
  postgres-data:
