// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dataaccess

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	UserID    pgtype.Int4
	SessionID string
	CreatedAt pgtype.Timestamp
	ExpiresAt pgtype.Timestamp
}

type User struct {
	UserID         int32
	Username       pgtype.Text
	PhoneNumber    string
	ProfilePicture pgtype.Text
}
