// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dataaccess

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID         int32
	Username       string
	PhoneNumber    string
	ProfilePicture pgtype.Text
}
