// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package dataaccess

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, phone_number)
VALUES ($1, $2)
RETURNING user_id
`

type CreateUserParams struct {
	Username    string
	PhoneNumber string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PhoneNumber)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}
