// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package dataaccess

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, phone_number)
VALUES ($1, $2)
RETURNING user_id
`

type CreateUserParams struct {
	Username    string
	PhoneNumber string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PhoneNumber)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const existsUserByPhoneNumber = `-- name: ExistsUserByPhoneNumber :one
SELECT EXISTS (SELECT 1 FROM users WHERE phone_number = $1) AS exists
`

func (q *Queries) ExistsUserByPhoneNumber(ctx context.Context, phoneNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserByPhoneNumber, phoneNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, phone_number, profile_picture FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PhoneNumber,
		&i.ProfilePicture,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT user_id, username, phone_number, profile_picture FROM users WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.PhoneNumber,
		&i.ProfilePicture,
	)
	return i, err
}
